services:
    tas2580.failedlogins.listener:
        class: tas2580\failedlogins\event\listener
        arguments:
            - @template
            - @user
            - @dbal.conn
            - @request
        tags:
            - { name: event.listener }
